### ISSUE TITLE
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ampledata** [ampledata/adsbcot#10]
```
>>> import pyModeS
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pyModeS/__init__.py", line 12, in <module>
    from .decoder import adsb
  File "/usr/local/lib/python3.9/dist-packages/pyModeS/decoder/adsb.py", line 19, in <module>
    from pyModeS.decoder.bds.bds05 import (
  File "/usr/local/lib/python3.9/dist-packages/pyModeS/decoder/bds/__init__.py", line 21, in <module>
    import numpy as np
  File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python"
  * The NumPy version is: "1.22.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory

```

**Comment by ampledata** [comment]
Fix: `sudo apt-get install libatlas-base-dev`
