### ISSUE TITLE
Debian package build is broken

### ISSUE THREAD

**Issue by ampledata** [ampledata/adsbcot#31]
```
running sdist_dsc
running egg_info
writing adsbcot.egg-info/PKG-INFO
writing dependency_links to adsbcot.egg-info/dependency_links.txt
writing entry points to adsbcot.egg-info/entry_points.txt
writing requirements to adsbcot.egg-info/requires.txt
writing top-level names to adsbcot.egg-info/top_level.txt
adding license file 'LICENSE' (matched pattern 'LICENSE')
reading manifest file 'adsbcot.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'requirements.txt'
writing manifest file 'adsbcot.egg-info/SOURCES.txt'
running sdist
running check
creating adsbcot-6.2.0b4
creating adsbcot-6.2.0b4/adsbcot.egg-info
copying files to adsbcot-6.2.0b4...
copying LICENSE -> adsbcot-6.2.0b4
copying MANIFEST.in -> adsbcot-6.2.0b4
copying README.rst -> adsbcot-6.2.0b4
copying setup.cfg -> adsbcot-6.2.0b4
copying setup.py -> adsbcot-6.2.0b4
copying adsbcot.egg-info/PKG-INFO -> adsbcot-6.2.0b4/adsbcot.egg-info
copying adsbcot.egg-info/SOURCES.txt -> adsbcot-6.2.0b4/adsbcot.egg-info
copying adsbcot.egg-info/dependency_links.txt -> adsbcot-6.2.0b4/adsbcot.egg-info
copying adsbcot.egg-info/entry_points.txt -> adsbcot-6.2.0b4/adsbcot.egg-info
copying adsbcot.egg-info/requires.txt -> adsbcot-6.2.0b4/adsbcot.egg-info
copying adsbcot.egg-info/top_level.txt -> adsbcot-6.2.0b4/adsbcot.egg-info
Writing adsbcot-6.2.0b4/setup.cfg
Creating tar archive
removing 'adsbcot-6.2.0b4' (and everything under it)
dpkg-buildpackage: info: source package adsbcot
dpkg-buildpackage: info: source version 6.2.0b4-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Greg Albrecht <oss@undef.net> <oss@undef.net>
 dpkg-source --before-build .
dpkg-source: info: using options from adsbcot-6.2.0b4/debian/source/options: --extend-diff-ignore=\.egg-info$
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=python_distutils
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/home/gba/src/SNS/adsbcot/deb_dist/adsbcot-6.2.0b4'
python3 setup.py clean -a
Traceback (most recent call last):
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/config.py", line 387, in _parse_attr
    return getattr(StaticModule(module_name), attr_name)
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/config.py", line 25, in __init__
    with open(spec.origin) as strm:
AttributeError: 'NoneType' object has no attribute 'origin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gba/src/SNS/adsbcot/deb_dist/adsbcot-6.2.0b4/setup.py", line 25, in <module>
    setup()
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gba/.pyenv/versions/3.9.6/lib/python3.9/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/dist.py", line 715, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/config.py", line 157, in parse_configuration
    meta.parse()
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/config.py", line 463, in parse
    section_parser_method(section_options)
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/config.py", line 436, in parse_section
    self[name] = value
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/config.py", line 220, in __setitem__
    value = parser(value)
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/config.py", line 552, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/config.py", line 390, in _parse_attr
    module = importlib.import_module(module_name)
  File "/home/gba/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'adsbcot'
make[1]: *** [debian/rules:10: override_dh_auto_clean] Error 1
make[1]: Leaving directory '/home/gba/src/SNS/adsbcot/deb_dist/adsbcot-6.2.0b4'
make: *** [debian/rules:7: clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
Traceback (most recent call last):
  File "/home/gba/src/SNS/adsbcot/setup.py", line 25, in <module>
    setup()
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gba/.pyenv/versions/3.9.6/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/gba/.pyenv/versions/3.9.6/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/gba/.pyenv/versions/3.9.6/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/stdeb/command/sdist_dsc.py", line 137, in run
    build_dsc(debinfo,
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/stdeb/util.py", line 1569, in build_dsc
    dpkg_buildpackage(*args, cwd=fullpath_repackaged_dirname)
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/stdeb/util.py", line 585, in dpkg_buildpackage
    process_command(args, cwd=cwd)
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/stdeb/util.py", line 226, in process_command
    check_call(args, cwd=cwd)
  File "/home/gba/.pyenv/versions/tak/lib/python3.9/site-packages/stdeb/util.py", line 59, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 2
```

**Comment by ampledata** [comment]
Fixed in v7.0.0
