### ISSUE TITLE
error building wheel for pymodes

### ISSUE THREAD

**Issue by VK1MIC** [ampledata/adsbcot#51]
Running `sudo python3 -m pip install adsbcot[with_pymodes]
`
ends with:

```
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'build.py']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymodes
Failed to build pymodes
ERROR: Could not build wheels for pymodes, which is required to install pyproject.toml-based projects
```

**Comment by VK1MIC** [comment]
full error 

sudo python3 -m pip install adsbcot[with_pymodes] 
[sudo] password for wade: 
Requirement already satisfied: adsbcot[with_pymodes] in /usr/lib/python3/dist-packages (8.0.2)
Requirement already satisfied: aircot>=1.2.0 in /usr/lib/python3/dist-packages (from adsbcot[with_pymodes]) (3.0.1)
Requirement already satisfied: pytak>=5.4.0 in /usr/lib/python3/dist-packages (from adsbcot[with_pymodes]) (7.1.0)
Collecting pymodes>=2.8
  Using cached pymodes-2.18.tar.gz (329 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.26
  Using cached numpy-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
Collecting pyzmq>=24.0
  Using cached pyzmq-26.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (868 kB)
Building wheels for collected packages: pymodes
  Building wheel for pymodes (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pymodes (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Compiling pyModeS/c_common.pyx because it depends on /tmp/pip-build-env-z3g7p_pi/overlay/local/lib/python3.10/dist-packages/Cython/Includes/libc/string.pxd.
      Compiling pyModeS/decoder/flarm/decode.pyx because it depends on /tmp/pip-build-env-z3g7p_pi/overlay/local/lib/python3.10/dist-packages/Cython/Includes/libc/string.pxd.
      [1/2] Cythonizing pyModeS/c_common.pyx
      [2/2] Cythonizing pyModeS/decoder/flarm/decode.pyx
      Traceback (most recent call last):
        File "/tmp/pip-install-qhd2eegk/pymodes_f0cfdd4cacbf40e6a8d29ce64ccb6a2f/build.py", line 67, in <module>
          build()
        File "/tmp/pip-install-qhd2eegk/pymodes_f0cfdd4cacbf40e6a8d29ce64ccb6a2f/build.py", line 58, in build
          for output in cmd.get_output_mapping():
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: get_output_mapping
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-z3g7p_pi/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
        File "/tmp/pip-build-env-z3g7p_pi/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-z3g7p_pi/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 123, in build
          self._build(zip_file)
        File "/tmp/pip-build-env-z3g7p_pi/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 172, in _build
          self._run_build_script(self._package.build_script)
        File "/tmp/pip-build-env-z3g7p_pi/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 262, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python3', 'build.py']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymodes
Failed to build pymodes
ERROR: Could not build wheels for pymodes, which is required to install pyproject.toml-based projects``

**Comment by PWRxPSYCHO** [comment]
https://github.com/junzis/pyModeS/issues/168

It looks like pymodes is not building. Which this project utilizes
